version: '3.8'

services:
  plex-recommendation: 
    image: williamcook/plex-recommendation:$TAG_VERSION
    build: 
      context: ./backend
      dockerfile: ./build/docker/Dockerfile
    restart: always 
    env_file:
      - path: ./.env
    ports:
      - "8090:8090"
    depends_on: 
      weaviate:
        condition: service_healthy
      postgres:
        condition: service_healthy
      
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.1
    ports:
    - 8080:8080
    - 50051:50051
    restart: on-failure:0
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-ollama'
      ENABLE_MODULES: 'text2vec-ollama'
      CLUSTER_HOSTNAME: 'node1'
    healthcheck:
      test: ["CMD", "wget", "-nv", "--spider", "http://weaviate:8080/v1/.well-known/ready"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 15s
      start_interval: 5s

  postgres:
    image: postgres
    restart: always
    env_file: .env
    ports:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ${PWD}/pg-data/:/var/lib/postgresql/data/